# Generated by Django 2.2 on 2021-05-24 13:13

from django.db import migrations, models
import utils.uploads


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210519_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.uploads.upload_instance, verbose_name='Изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
